Repository Thenlie/turtle, pull requests merged in 2022-04, with the labels that each got.

#10 Feature/endgame
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/components/EndGame/Message/Message.jsx
  client/src/components/EndGame/Message/index.js
  client/src/components/EndGame/index.js
  client/src/components/Game/Display/Display.jsx
  client/src/pages/ContGame.js
  client/src/pages/DailyGame.js
  client/src/pages/EndGame.js
  client/src/utils/mutations.js
  server/models/Scores.js
  server/models/index.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#13 Feature/flags
  client/package-lock.json
  client/package.json
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/controllers/api/auth.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#15 8 feature/profile page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Info/index.js
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Scores/index.js
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/Profile/Stats/index.js
  client/src/components/Profile/index.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
  client/src/utils/helper.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/controllers/api/auth.js
  server/models/User.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement, component

#19 Feature/seeder
  README.md
  server/__tests__/Score.test.js
  server/__tests__/User.test.js
  server/lib/ScoreObj.js
  server/lib/UserObj.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/seeders/seeds.js
  server/utils/helpers.js
Labels: enhancement

#20 17 feature/profile stats
  README.md
  client/package-lock.json
  client/package.json
  client/src/components/Game/Display/Display.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Stats/Calendar.jsx
  client/src/components/Profile/Stats/Charts.jsx
  client/src/components/Profile/Stats/Info.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/ProfileCharts/GameChart.jsx
  client/src/components/ProfileCharts/GuessChart.jsx
  client/src/components/ProfileCharts/index.js
  client/src/index.css
  client/src/pages/Profile.js
  client/src/utils/helper.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/__tests__/Score.test.js
  server/__tests__/User.test.js
  server/lib/ScoreObj.js
  server/lib/UserObj.js
  server/models/Scores.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/seeds.js
  server/utils/helpers.js
Labels: enhancement, component

#22 Created mobile responsiveness for Profile page and components
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Stats/Calendar.jsx
  client/src/components/Profile/Stats/Info.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/pages/Profile.js
Labels: refactor, restyle

#23 Feature/endgame
  client/package-lock.json
  client/package.json
  client/src/components/Charts/EndGameChart/EndGameChart.jsx
  client/src/components/Charts/EndGameChart/index.js
  client/src/components/Charts/index.js
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/pages/EndGame.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/models/Scores.js
  server/schemas/typeDefs.js
Labels: enhancement, component

#24 8 feature/profile page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Logout/Logout.jsx
  client/src/components/Game/Display/Display.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Stats/Calendar.jsx
  client/src/components/Profile/Stats/Charts.jsx
  client/src/components/Profile/Stats/Info.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/ProfileCharts/GameChart.jsx
  client/src/components/ProfileCharts/GuessChart.jsx
  client/src/components/ProfileCharts/index.js
  client/src/index.css
  client/src/pages/Profile.js
  client/src/utils/helper.js
  client/src/utils/queries.js
  server/__tests__/Score.test.js
  server/lib/ScoreObj.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/utils/helpers.js
Labels: enhancement, component

#25 Develop
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Charts/EndGameChart/EndGameChart.jsx
  client/src/components/Charts/EndGameChart/index.js
  client/src/components/Charts/index.js
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Logout/Logout.jsx
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Game/Display/Display.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Info/index.js
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Scores/index.js
  client/src/components/Profile/Stats/Calendar.jsx
  client/src/components/Profile/Stats/Charts.jsx
  client/src/components/Profile/Stats/Info.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/Profile/Stats/index.js
  client/src/components/Profile/index.js
  client/src/components/ProfileCharts/GameChart.jsx
  client/src/components/ProfileCharts/GuessChart.jsx
  client/src/components/ProfileCharts/index.js
  client/src/index.css
  client/src/pages/EndGame.js
  client/src/pages/Home.js
  client/src/pages/Profile.js
  client/src/utils/helper.js
  client/src/utils/mutations.js
  client/src/utils/queries.js
  server/__tests__/Score.test.js
  server/__tests__/User.test.js
  server/controllers/api/auth.js
  server/lib/ScoreObj.js
  server/lib/UserObj.js
  server/models/Scores.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/seeders/seeds.js
  server/utils/helpers.js
Labels: enhancement, component

#27 26 refactor/endgame chart
  client/src/App.js
  client/src/components/Charts/EndGameChart/EndGameChart.jsx
  client/src/components/Charts/EndGameChart/index.js
  client/src/components/Charts/GamePerDayChart/GamePerDayChart.jsx
  client/src/components/Charts/GamePerDayChart/index.js
  client/src/components/Charts/GuessPerDayChart/GuessPerDayChart.jsx
  client/src/components/Charts/GuessPerDayChart/index.js
  client/src/components/Charts/GuessPerGameChart/GuessPerGameChart.jsx
  client/src/components/Charts/GuessPerGameChart/index.js
  client/src/components/Charts/index.js
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/components/EndGame/Message/Message.jsx
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Game/Display/Display.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Stats/Charts.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/ProfileCharts/index.js
  client/src/pages/EndGame.js
  client/src/pages/Profile.js
  server/utils/helpers.js
Labels: enhancement, refactor

#29 28 refactor/login signup
  client/src/App.js
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Logout/Logout.jsx
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Header/DropdownMenu.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/Navigation.jsx
  client/src/pages/Forms.js
  client/src/pages/NotFound.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
  server/controllers/api/auth.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: refactor

#33 16 feature/landing page
  client/public/index.html
  client/src/index.css
  client/src/pages/Home.js
Labels: enhancement, refactor

#34 30 refactor/game
  client/public/index.html
  client/src/App.js
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/index.js
  client/src/components/Game/Display/Display.jsx
  client/src/components/Game/UserInput/UserInput.jsx
  client/src/pages/Home.js
Labels: refactor, restyle

#39 37 refactor/route protection
  client/src/App.js
  client/src/pages/Home.js
  server/controllers/api/auth.js
Labels: bug, refactor

#40 36 feature/lockout
  client/src/App.js
  client/src/components/LockOut/LockOut.jsx
  client/src/components/LockOut/index.js
  client/src/pages/DailyGame.js
  client/src/pages/Game.js
Labels: enhancement

#41 Refactor/404
  client/src/components/LockOut/LockOut.jsx
  client/src/pages/NotFound.js
Labels: refactor, restyle

#42 Update README.md
  README.md
Labels: enhancement

#43 Feature/endgame
  client/src/components/Charts/GuessPerGameChart/GuessPerGameChart.jsx
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/components/EndGame/Message/Message.jsx
  client/src/pages/EndGame.js
Labels: enhancement, component

#45 18 feature/pwa
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/svcWorker.js
Labels: enhancement, component

#48 Develop
  README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/svcWorker.js
  client/src/App.js
  client/src/components/Charts/EndGameChart/EndGameChart.jsx
  client/src/components/Charts/EndGameChart/index.js
  client/src/components/Charts/GamePerDayChart/GamePerDayChart.jsx
  client/src/components/Charts/GamePerDayChart/index.js
  client/src/components/Charts/GuessPerDayChart/GuessPerDayChart.jsx
  client/src/components/Charts/GuessPerDayChart/index.js
  client/src/components/Charts/GuessPerGameChart/GuessPerGameChart.jsx
  client/src/components/Charts/GuessPerGameChart/index.js
  client/src/components/Charts/index.js
  client/src/components/EndGame/GameInfo/GameInfo.jsx
  client/src/components/EndGame/Message/Message.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/index.js
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Logout/Logout.jsx
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Game/Display/Display.jsx
  client/src/components/Game/UserInput/UserInput.jsx
  client/src/components/Header/DropdownMenu.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/LockOut/LockOut.jsx
  client/src/components/LockOut/index.js
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Stats/Charts.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/components/ProfileCharts/index.js
  client/src/index.css
  client/src/pages/ContGame.js
  client/src/pages/DailyGame.js
  client/src/pages/EndGame.js
  client/src/pages/Forms.js
  client/src/pages/Game.js
  client/src/pages/Home.js
  client/src/pages/NotFound.js
  client/src/pages/Profile.js
  client/src/utils/queries.js
  server/controllers/api/auth.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
  server/utils/helpers.js
Labels: enhancement

#52 Revert "6 refactor header and navigation"
  client/src/App.css
  client/src/App.js
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/DropdownMenu.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/Navigation.jsx
Labels: bug

#53 Feature/header 2
  client/src/App.css
  client/src/App.js
  client/src/components/Charts/GamePerDayChart/GamePerDayChart.jsx
  client/src/components/Charts/GuessPerDayChart/GuessPerDayChart.jsx
  client/src/components/Forms/Login/Login.jsx
  client/src/components/Forms/Signup/Signup.jsx
  client/src/components/Header/DropdownMenu.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/Navigation.jsx
  client/src/components/LockOut/LockOut.jsx
  client/src/components/Profile/Info/Info.jsx
  client/src/components/Profile/Scores/Scores.jsx
  client/src/components/Profile/Stats/Calendar.jsx
  client/src/components/Profile/Stats/Info.jsx
  client/src/components/Profile/Stats/Stats.jsx
  client/src/pages/ContGame.js
  client/src/pages/DailyGame.js
  client/src/pages/Home.js
  client/src/pages/NotFound.js
  client/src/pages/Profile.js
Labels: component, refactor, restyle
